### ISSUE TITLE
more of a request..

### ISSUE THREAD

**Issue by raymondoo** [dgkanatsios/AngryBirdsClone#1]
Is there anychance someone can add a star rating system to this basicly at the end of a level the uses will recive up to 3 stars depending on the time they take to complete the level or simulour i have tried my self but went really wrong

**Comment by dgkanatsios** [comment]
Did you have any change in getting it to work? Basically, you need to get the time that the level has started, the level that has been successfully completed and find a formula to assign a proper start. I'm closing it as it's more of a feature request than an issue with the code itself.
