### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by ClearSoulgx** [dgkanatsios/AngryBirdsClone#3]
Hello,
I hava two questions and I hope you can help me.
The First question
how to use "using Assest Scripts",when I  use it,ide tell me it is wrong
the second queston
when I write "Public SlingshotState slingshotstate",it tells me there are not Slingshotstate

**Comment by zloivan** [comment]
Any screen shots or context?

Отправлено с iPhone

**Comment by dgkanatsios** [comment]
Did you fix your issues? I'm closing this for now, feel free to re-open
